### ISSUE TITLE
Couldn't make it work from a markdown code block.

### ISSUE THREAD

**Issue by mpenna** [pomdtr/vscode-markdown-kroki#9] opened 2023-07-18 21:43 UTC
I'm testing out this extension along with a Dockerized instance of  Kroki. I have setup two containers on the same bridged network, thus they can see each other: 

- one container running kroki (I'm using the docker-compose.yml available on Kroki's site, which pulls up all the other auxiliary services)
- a second container, with Node and other goodies, which I use as a workspace

Despite having configured this extension's settings with the URL of the Kroki container, along with a "kroki-" prefix, while working inside VSCode and attached to the workspace container, nothing happens when I for instance add a "kroki-blockdialog" code block to a markdown file:

```kroki-blockdiag
blockdiag {
  blockdiag -> generates -> "block-diagrams";
  blockdiag -> is -> "very easy!";

  blockdiag [color = "greenyellow"];
  "block-diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}
```

Issuing a simple GET request against the Kroki container from the workspace container's terminal (via curl) works without issues.

Any ideas what could be the issue here? Is it possible to debug the extension to see if something is breaking?

**Comment by albbino** [comment] 2023-08-10 20:32
Same Problem to ne.

**Comment by acmnu** [comment] 2024-01-05 10:04
@mpenna As far as I know, you shouldn't say "blockdiag" again when we are talking about Markdown:

That is original structurizr format 
```
blockdiag {
  blockdiag -> generates -> "block-diagrams";
  blockdiag -> is -> "very easy!";

  blockdiag [color = "greenyellow"];
  "block-diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}
```

And that is the format of *embedded* kroki structurizr:

<pre>
```kroki-blockdiag
{
  blockdiag -> generates -> "block-diagrams";
  blockdiag -> is -> "very easy!";

  blockdiag [color = "greenyellow"];
  "block-diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}
```
</pre>

**Comment by pomdtr** [comment] 2024-01-30 22:38
@mpenna @albbino did you test the suggestion ? Closing it for now, I'll reopen if the issue is not resolved

**Closed** 2024-01-30 22:38 UTC
